name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: pip3 install jsonschema-cli
      - run: |
          for directory in base16 holiday standard warp_bundled; do
            env -C "$directory" jsonschema-cli validate "../schemas/theme.json" *.yaml
          done
